Improve ingredient ux
ethicodeorg/foodprint-calculator pull request #21
Opened 2020-11-06 17:48 UTC by dh4u

HI @atlisg - I hope that I am doing this correctly. I am submitting a request for you to review my branch and pull it into the base code if all is well. Thanks, Scott

2020-11-06 23:58 UTC, atlisg requested changes
It seems that your PR is negating my last PR, adding french to the page. Some Git mix-up there?

Congrats on your first Ethicode PR! Coming along nicely, I see.

2020-11-06 23:58 UTC, atlisg commented on components/Ingredients.js
> +    {!ingredients.length ? (<><Separator /><div className="ingredient-basic">{t('no_ingredient')}</div></>) : '' }
I think we should skip this Separator here, just add a bit of padding around "No ingredients added" so that it has the same space as an actual ingredient. Also, maybe it'd be better to have "No ingredients added yet"?

Also, instead of using the ternary, you could simplify a bit:
`{!ingredients.length && <div className="ingredient-basic">{t('no_ingredient')}</div>}`

2020-11-06 23:58 UTC, atlisg commented on components/MealForm.js
> +import {
I prefer `import { setFocus } from '../utils/ui';`

2020-11-06 23:58 UTC, atlisg commented on components/MealForm.js
> +  // https://app.asana.com/0/1192620845659633/1199082523477129 - Automatically move the focus to the next input when an ingredient has been selected
The line is too long, let's try to keep them at a 100 chars max. Also, we shouldn't put links to Asana tasks in comments, that would quickly grow into a monster of Asana links in the code. However, I love Asana links in PR descriptions! 😄

2020-11-06 23:58 UTC, atlisg commented on components/MealForm.js
> +                    defaultMenuIsOpen="true"
Instead of opening the menu, could we just move the focus to the input, so the user can start typing right away? I think most users are gonna use it like that more often than scrolling the menu every time.

2020-11-06 23:58 UTC, atlisg commented on public/static/locales/en/common.json
> +  "meal_name": "Meal name (required)",
Nice! Did we talk about this? I remember thinking about adding this but I don't remember talking about it or writing it anywhere. Did you just hack my mind?

2020-11-09 14:32 UTC, dh4u commented
> It seems that your PR is negating my last PR, adding french to the page. Some Git mix-up there?
> 
> Congrats on your first Ethicode PR! Coming along nicely, I see.

So - regarding French - I don't mean to blame - however the "prettier" commit added a lot more than just prettier - https://github.com/ethicodeorg/foodprint-calculator/pull/21/commits/ebcb2086940bf8e4fbad9ebf21f132da5f23c97f and I'm not entirely sure what happened there. I would have thought that the merge would have pulled one file and when I look at the commit it seems there was a bit more - https://github.com/ethicodeorg/foodprint-calculator/commit/1e9252305a419a49c25a384f50bf19b4e8b1e0a9

I will revert the "prettier" commit I made to my branch and correct from there.

2020-11-09 14:35 UTC, dh4u commented on components/Ingredients.js
> +    {!ingredients.length ? (<><Separator /><div className="ingredient-basic">{t('no_ingredient')}</div></>) : '' }
> I think we should skip this Separator here, just add a bit of padding around "No ingredients added" so that it has the same space as an actual ingredient. Also, maybe it'd be better to have "No ingredients added yet"?
> 
> Also, instead of using the ternary, you could simplify a bit:
> `{!ingredients.length && <div className="ingredient-basic">{t('no_ingredient')}</div>}`

Thanks! I was wrongly focused on making it ternary. I will make that change.

2020-11-09 14:36 UTC, dh4u commented on components/Ingredients.js
> +    {!ingredients.length ? (<><Separator /><div className="ingredient-basic">{t('no_ingredient')}</div></>) : '' }
Thanks! I was wrongly focused on making it ternary. I will make that change.

2020-11-09 14:37 UTC, atlisg commented
Yes, I think we should never pull from one open PR into another. The way I like to work is just branch out for what you are working on, then if you need something from master, run `git rebase master` on your branch. At least that works for me to make my life easier. 😉

2020-11-09 14:38 UTC, dh4u commented on public/static/locales/en/common.json
> +  "meal_name": "Meal name (required)",
It seemed like the thing to do... ;)

2020-11-09 14:57 UTC, dh4u commented on components/MealForm.js
> +  // https://app.asana.com/0/1192620845659633/1199082523477129 - Automatically move the focus to the next input when an ingredient has been selected
Will change in my PR and will do for the future.

I was trying to look at it as if I was new to the team and code. 
// automatically move the focus
// automatically move the focus - asana - http ... app.asana.com/0/1192620845659633/1199082523477129
// automatically move the focus - PR http ... GitHub.com/pr#

In the first case I as a new developer have no idea where the requirement came from or any discussions involved around it. 

In the second and third cases I do know where the requirement came from and the discussions around it - however - I do not know if the third is a possibility if even wanted because I would need a pull request variable that I can be replaced in the code comment.

2020-11-09 15:09 UTC, dh4u commented on components/MealForm.js
> +import {
👍🏾

2020-11-09 15:10 UTC, dh4u commented on components/MealForm.js
> +                    defaultMenuIsOpen="true"
👍🏾

2020-11-09 15:33 UTC, dh4u commented on components/MealForm.js
> +  // https://app.asana.com/0/1192620845659633/1199082523477129 - Automatically move the focus to the next input when an ingredient has been selected
https://github.com/ethicodeorg/foodprint-calculator/commit/1950f15b3c4fa16eb0b9a646da46e03f1dea4dac

2020-11-09 15:34 UTC, dh4u commented on public/static/locales/en/common.json
> +  "meal_name": "Meal name (required)",
Modified to "No ingredients added yet" - https://github.com/ethicodeorg/foodprint-calculator/commit/3d41b5760b1ffc58fbad9404d84c8f4fb16fa630

2020-11-09 15:35 UTC, dh4u commented on components/MealForm.js
> +import {
https://github.com/ethicodeorg/foodprint-calculator/commit/d29c530ded703dfb6c27e0a9b084c17625a3ee70

2020-11-09 15:49 UTC, dh4u commented
> > It seems that your PR is negating my last PR, adding french to the page. Some Git mix-up there?
> > Congrats on your first Ethicode PR! Coming along nicely, I see.
> 
> So - regarding French - I don't mean to blame - however the "prettier" commit added a lot more than just prettier - [ebcb208](https://github.com/ethicodeorg/foodprint-calculator/commit/ebcb2086940bf8e4fbad9ebf21f132da5f23c97f) and I'm not entirely sure what happened there. I would have thought that the merge would have pulled one file and when I look at the commit it seems there was a bit more - [1e92523](https://github.com/ethicodeorg/foodprint-calculator/commit/1e9252305a419a49c25a384f50bf19b4e8b1e0a9)
> 
> I will revert the "prettier" commit I made to my branch and correct from there.

I had already reverted my prettier commit so now I'm curious... what was negated in the other PR?

2020-11-09 15:57 UTC, dh4u commented
> Yes, I think we should never pull from one open PR into another. The way I like to work is just branch out for what you are working on, then if you need something from master, run `git rebase master` on your branch. At least that works for me to make my life easier. 😉

I agree with everything you just said... I wasn't trying to pull anything from another PR

It looks like the "prettier" code came from master and perhaps you accidentally got some of your PR in there when you did the commit for prettier - https://github.com/ethicodeorg/foodprint-calculator/commit/1e9252305a419a49c25a384f50bf19b4e8b1e0a9 

🤷🏾‍♂️

2020-11-09 16:37 UTC, dh4u commented on components/Ingredients.js
> +    {!ingredients.length ? (<><Separator /><div className="ingredient-basic">{t('no_ingredient')}</div></>) : '' }
Padding... https://github.com/ethicodeorg/foodprint-calculator/commit/d5686a369cdf88971d58f742639c373b06f522e4

2020-11-11 21:10 UTC, dh4u commented
Closing - superseded by https://github.com/ethicodeorg/foodprint-calculator/pull/23

2020-11-11 21:10 UTC, closed without merging